name: kolam_ikan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1

  # Charts & visualization
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^31.1.19
  syncfusion_flutter_gauges: ^31.1.19

  # Date/time
  intl: ^0.20.2

  # MQTT
  mqtt_client: ^10.2.0

  # HTTP
  http: ^1.1.0
  dio: ^5.4.0

  # Images
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Local storage
  shared_preferences: ^2.2.2

  # Permissions
  permission_handler: ^12.0.1

  # File & storage
  path_provider: ^2.1.1
  excel: ^4.0.6           # <- untuk export Excel
  pdf: ^3.11.0            # <- untuk generate PDF
  printing: ^5.11.0       # <- untuk menyimpan/print PDF

  # UI Components
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
