// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvAzHtVasHVBxrpKkchwpLTiB-G9mn5Fg',
    appId: '1:685083671333:web:da7c7d6b6c3d49f313b8cc',
    messagingSenderId: '685083671333',
    projectId: 'kolam-ikan-project',
    authDomain: 'kolam-ikan-project.firebaseapp.com',
    storageBucket: 'kolam-ikan-project.firebasestorage.app',
    measurementId: 'G-F9S3ML5JMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErG_NUlPZjED5zDhWUzPKyFkkusp4PqM',
    appId: '1:685083671333:android:128e62df10ff5f2813b8cc',
    messagingSenderId: '685083671333',
    projectId: 'kolam-ikan-project',
    storageBucket: 'kolam-ikan-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvAzHtVasHVBxrpKkchwpLTiB-G9mn5Fg',
    appId: '1:685083671333:web:6a2e4a987a8b2f9e13b8cc',
    messagingSenderId: '685083671333',
    projectId: 'kolam-ikan-project',
    authDomain: 'kolam-ikan-project.firebaseapp.com',
    storageBucket: 'kolam-ikan-project.firebasestorage.app',
    measurementId: 'G-H9PE2CQ9SZ',
  );
}
